version: '3.7'

services:
  script:
    build: .
    image: sanarisan/ts-backend-v2:1
    restart: always
    ports:
      - '3000:3000'
    command: >
      sh -c "yarn cli-wipe-linux &&
          yarn launch-prod"

