const enum ERROR_ORIGIN {
	EXTERNAL = "EXTERNAL",
	INTERNAL = "INTERNAL",
}

const enum ERROR_TYPE {
	REQUEST = "REQUEST",
	NO_DATA = "NO_DATA",
	NO_RESPONSE = "NO_RESPONSE",
	NO_RESULT = "NO_RESULT",
	BAD_STATUS = "BAD_STATUS",
	NO_SUCCESS = "NO_SUCCESS",
	CLI_NO_ENTRY = "CLI_NO_ENTRY",
}

export { ERROR_ORIGIN, ERROR_TYPE };
